# Generated by Django 3.2.8 on 2021-10-21 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=None, max_length=100, null=True)),
                ('image', models.ImageField(default=None, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=None, max_length=100, null=True)),
                ('image', models.ImageField(default=None, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Programador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=None, max_length=100, null=True)),
                ('image', models.ImageField(default=None, null=True, upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Sala',
        ),
        migrations.RenameField(
            model_name='jugadores',
            old_name='jugador',
            new_name='nombreJugador',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='image_error',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='image_modulo',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='image_programador',
        ),
        migrations.AddField(
            model_name='jugadores',
            name='estado',
            field=models.BooleanField(default='True', null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='error',
            field=models.ForeignKey(db_column='Error', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='principal.error'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='modulo',
            field=models.ForeignKey(db_column='Modulo', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='principal.modulo'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='programador',
            field=models.ForeignKey(db_column='Programador', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='principal.programador'),
        ),
    ]
