# Generated by Django 3.2.8 on 2021-10-21 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_auto_20211021_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jugadores',
            old_name='nombreJugador',
            new_name='nombre',
        ),
    ]
